name: ci

on:
  push:
    branches: ["development"]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3-bullseye
    steps:
      - name: get Python version
        run: python -V
