name: ci

on:
  push:
    branches: ["development"]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3-bullseye
    services:
      db:
        image: postgres:13-bullseye
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: install dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt

      - name: django check
        run: python manage.py check

      - name: django migrate
        run: python manage.py migrate
        env:
          POSTGRES_HOST: db
          POSTGRES_PORT: 5432
          POSTGRES_NAME: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

      - name: django test (with coverage)
        run: coverage run --include 'main/*' manage.py test
        env:
          POSTGRES_HOST: db
          POSTGRES_PORT: 5432
          POSTGRES_NAME: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

      - name: coverage report
        run: coverage report --show-missing
