name: ci

on:
  push:
    branches: ["development"]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3-bullseye
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: install dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt

      - name: django check
        run: python manage.py check
